# Generated by Django 5.1.4 on 2025-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=13)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
